import type {Metadata} from "next";
import './globals.css';
import {Geist} from 'next/font/google';
import {cn} from '@/lib/utils';
import RootProvider from '@/providers/root-providers';
import {Toaster} from '@/components/ui/toast';
import AppHeader from '@/components/shared/header';

const geist = Geist({ subsets: ["latin"], variable: '--font-sans'});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: LayoutProps<'/'>){
  return (
    <html lang="en" className={cn('h-full antialiased', 'font-sans', geist.variable)}>
      <body className="min-h-dvh">
        <RootProvider>
          <main className="min-h-dvh grid bg-background text-foreground grid-rows-[auto_1fr]">
            <AppHeader />
            {children}
            <Toaster />
          </main>
        </RootProvider>
      </body>
    </html>
  )
}